export const BannerItem = [
  {
    id: "33175",
    label: "Đổi Điểm Thi THPT Nhận Siêu Ưu Đãi",
    imageUrl: "image/banner/2.jpg",
    url: "https://phongvu.vn/p/uu-dai-doi-diem-thpt",
    width: "1920",
    height: "566",
    redirectUrl: "https://phongvu.vn/p/uu-dai-doi-diem-thpt",
  },
  {
    id: "33164",
    label: "Vòng quay trúng lớn",
    imageUrl: "image/banner/3.jpg",
    url: "https://phongvu.vn/p/lucky-draw",
    width: "1920",
    height: "566",
    redirectUrl: "https://phongvu.vn/p/lucky-draw",
  },
  {
    id: "33088",
    label: "Giờ Vàng Giá Sốc",
    imageUrl: "image/banner/4.jpg",
    url: "https://phongvu.vn/p/super-sale?utm_source=homepage\u0026utm_medium=mb-main-banner\u0026utm_campaign=super-sale-1124",
    redirectUrl:
      "https://phongvu.vn/p/super-sale?utm_source=homepage\u0026utm_medium=mb-main-banner\u0026utm_campaign=super-sale-1124",
  },
  {
    id: "33096",
    label: "Xả tồn kho",
    imageUrl: "image/banner/5.jpg",
    url: "https://phongvu.vn/p/sieu-sale-phong-vu",
    width: "1920",
    height: "566",
    redirectUrl: "https://phongvu.vn/p/sieu-sale-phong-vu",
  },
  {
    id: "32630",
    label: "Siêu hội PC Tháng 3,4",
    imageUrl: "image/banner/6.jpg",
    url: "https://phongvu.vn/c/may-tinh-de-ban",
    width: "1920",
    height: "566",
    redirectUrl: "https://phongvu.vn/c/may-tinh-de-ban",
  },
  {
    id: "33229",
    label: "Build PC theo nhu cầu",
    imageUrl: "image/banner/7.jpg",
    url: "https://phongvu.vn/buildpc",
    width: "1920",
    height: "566",
    redirectUrl: "https://phongvu.vn/buildpc",
  },
];
