export const GET_ALL_ATTRIBUTES_REQUEST = "GET_ALL_ATTRIBUTES_REQUEST";
export const GET_ALL_ATTRIBUTES_SUCCESS = "GET_ALL_ATTRIBUTES_SUCCESS";
export const GET_ALL_ATTRIBUTES_FAILURE = "GET_ALL_ATTRIBUTES_FAILURE";

export const ADD_NEW_ATTRIBUTE_REQUEST = "ADD_NEW_ATTRIBUTE_REQUEST";
export const ADD_NEW_ATTRIBUTE_SUCCESS = "ADD_NEW_ATTRIBUTE_SUCCESS";
export const ADD_NEW_ATTRIBUTE_FAILURE = "ADD_NEW_ATTRIBUTE_FAILURE";

export const GET_ATTRIBUTE_REQUEST = "GET_ATTRIBUTE_REQUEST";
export const GET_ATTRIBUTE_SUCCESS = "GET_ATTRIBUTE_SUCCESS";
export const GET_ATTRIBUTE_FAILURE = "GET_ATTRIBUTE_FAILURE";

export const UPDATE_ATTRIBUTE_REQUEST = "UPDATE_ATTRIBUTE_REQUEST";
export const UPDATE_ATTRIBUTE_SUCCESS = "UPDATE_ATTRIBUTE_SUCCESS";
export const UPDATE_ATTRIBUTE_FAILURE = "UPDATE_ATTRIBUTE_FAILURE";

export const DELETE_ATTRIBUTE_REQUEST = "DELETE_ATTRIBUTE_REQUEST";
export const DELETE_ATTRIBUTE_SUCCESS = "DELETE_ATTRIBUTE_SUCCESS";
export const DELETE_ATTRIBUTE_FAILURE = "DELETE_ATTRIBUTE_FAILURE";
